import {
  SyntaxKind,
  NodeFlags,
  Node,
  factory,
} from "typescript";

/**
 * Cloudflare D1 Database Management Functions
 *
 * These functions are automatically generated alongside your query code
 * to support multi-tenancy and database lifecycle management.
 *
 * @see https://developers.cloudflare.com/api/resources/d1/subresources/database/
 */

export function generateManagementTypes(): Node[] {
  const nodes: Node[] = [];

  // D1Database interface
  nodes.push(
    factory.createInterfaceDeclaration(
      [factory.createToken(SyntaxKind.ExportKeyword)],
      factory.createIdentifier("D1Database"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("uuid"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("name"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("version"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("created_at"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("num_tables"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.NumberKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("file_size"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.NumberKeyword)
        ),
      ]
    )
  );

  // CreateDatabaseRequest interface
  nodes.push(
    factory.createInterfaceDeclaration(
      [factory.createToken(SyntaxKind.ExportKeyword)],
      factory.createIdentifier("CreateDatabaseRequest"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("name"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("primary_location_hint"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
      ]
    )
  );

  // UpdateDatabaseRequest interface
  nodes.push(
    factory.createInterfaceDeclaration(
      [factory.createToken(SyntaxKind.ExportKeyword)],
      factory.createIdentifier("UpdateDatabaseRequest"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("name"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
      ]
    )
  );

  // ListDatabasesOptions interface
  nodes.push(
    factory.createInterfaceDeclaration(
      [factory.createToken(SyntaxKind.ExportKeyword)],
      factory.createIdentifier("ListDatabasesOptions"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("page"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.NumberKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("per_page"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.NumberKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("name"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword)
        ),
      ]
    )
  );

  return nodes;
}

export function generateManagementFunctions(): Node[] {
  const nodes: Node[] = [];

  // createDatabase function
  nodes.push(
    factory.createFunctionDeclaration(
      [
        factory.createToken(SyntaxKind.ExportKeyword),
        factory.createToken(SyntaxKind.AsyncKeyword),
      ],
      undefined,
      factory.createIdentifier("createDatabase"),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("client"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1HttpClient"),
            undefined
          ),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("request"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("CreateDatabaseRequest"),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(factory.createIdentifier("Promise"), [
        factory.createTypeReferenceNode(
          factory.createIdentifier("D1Database"),
          undefined
        ),
      ]),
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("url"),
                  undefined,
                  undefined,
                  factory.createTemplateExpression(
                    factory.createTemplateHead(
                      "https://api.cloudflare.com/client/v4/accounts/"
                    ),
                    [
                      factory.createTemplateSpan(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("client"),
                          factory.createIdentifier("accountId")
                        ),
                        factory.createTemplateTail("/d1/database")
                      ),
                    ]
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("fetchFn"),
                  undefined,
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("client"),
                      factory.createIdentifier("fetch")
                    ),
                    factory.createToken(SyntaxKind.BarBarToken),
                    factory.createIdentifier("fetch")
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("response"),
                  undefined,
                  undefined,
                  factory.createAwaitExpression(
                    factory.createCallExpression(
                      factory.createIdentifier("fetchFn"),
                      undefined,
                      [
                        factory.createIdentifier("url"),
                        factory.createObjectLiteralExpression(
                          [
                            factory.createPropertyAssignment(
                              factory.createIdentifier("method"),
                              factory.createStringLiteral("POST")
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("headers"),
                              factory.createObjectLiteralExpression(
                                [
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Authorization"),
                                    factory.createTemplateExpression(
                                      factory.createTemplateHead("Bearer "),
                                      [
                                        factory.createTemplateSpan(
                                          factory.createPropertyAccessExpression(
                                            factory.createIdentifier("client"),
                                            factory.createIdentifier("apiToken")
                                          ),
                                          factory.createTemplateTail("")
                                        ),
                                      ]
                                    )
                                  ),
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Content-Type"),
                                    factory.createStringLiteral("application/json")
                                  ),
                                ],
                                true
                              )
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("body"),
                              factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                  factory.createIdentifier("JSON"),
                                  factory.createIdentifier("stringify")
                                ),
                                undefined,
                                [factory.createIdentifier("request")]
                              )
                            ),
                          ],
                          true
                        ),
                      ]
                    )
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("data"),
                  undefined,
                  undefined,
                  factory.createAsExpression(
                    factory.createAwaitExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("response"),
                          factory.createIdentifier("json")
                        ),
                        undefined,
                        undefined
                      )
                    ),
                    factory.createKeywordTypeNode(SyntaxKind.AnyKeyword)
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createReturnStatement(
            factory.createAsExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier("data"),
                factory.createIdentifier("result")
              ),
              factory.createTypeReferenceNode(
                factory.createIdentifier("D1Database"),
                undefined
              )
            )
          ),
        ],
        true
      )
    )
  );

  // deleteDatabase function
  nodes.push(
    factory.createFunctionDeclaration(
      [
        factory.createToken(SyntaxKind.ExportKeyword),
        factory.createToken(SyntaxKind.AsyncKeyword),
      ],
      undefined,
      factory.createIdentifier("deleteDatabase"),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("client"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1HttpClient"),
            undefined
          ),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("databaseId"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(factory.createIdentifier("Promise"), [
        factory.createKeywordTypeNode(SyntaxKind.VoidKeyword),
      ]),
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("url"),
                  undefined,
                  undefined,
                  factory.createTemplateExpression(
                    factory.createTemplateHead(
                      "https://api.cloudflare.com/client/v4/accounts/"
                    ),
                    [
                      factory.createTemplateSpan(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("client"),
                          factory.createIdentifier("accountId")
                        ),
                        factory.createTemplateMiddle("/d1/database/")
                      ),
                      factory.createTemplateSpan(
                        factory.createIdentifier("databaseId"),
                        factory.createTemplateTail("")
                      ),
                    ]
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("fetchFn"),
                  undefined,
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("client"),
                      factory.createIdentifier("fetch")
                    ),
                    factory.createToken(SyntaxKind.BarBarToken),
                    factory.createIdentifier("fetch")
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createExpressionStatement(
            factory.createAwaitExpression(
              factory.createCallExpression(
                factory.createIdentifier("fetchFn"),
                undefined,
                [
                  factory.createIdentifier("url"),
                  factory.createObjectLiteralExpression(
                    [
                      factory.createPropertyAssignment(
                        factory.createIdentifier("method"),
                        factory.createStringLiteral("DELETE")
                      ),
                      factory.createPropertyAssignment(
                        factory.createIdentifier("headers"),
                        factory.createObjectLiteralExpression(
                          [
                            factory.createPropertyAssignment(
                              factory.createStringLiteral("Authorization"),
                              factory.createTemplateExpression(
                                factory.createTemplateHead("Bearer "),
                                [
                                  factory.createTemplateSpan(
                                    factory.createPropertyAccessExpression(
                                      factory.createIdentifier("client"),
                                      factory.createIdentifier("apiToken")
                                    ),
                                    factory.createTemplateTail("")
                                  ),
                                ]
                              )
                            ),
                          ],
                          true
                        )
                      ),
                    ],
                    true
                  ),
                ]
              )
            )
          ),
        ],
        true
      )
    )
  );

  // updateDatabase function
  nodes.push(
    factory.createFunctionDeclaration(
      [
        factory.createToken(SyntaxKind.ExportKeyword),
        factory.createToken(SyntaxKind.AsyncKeyword),
      ],
      undefined,
      factory.createIdentifier("updateDatabase"),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("client"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1HttpClient"),
            undefined
          ),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("databaseId"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("request"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("UpdateDatabaseRequest"),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(factory.createIdentifier("Promise"), [
        factory.createTypeReferenceNode(
          factory.createIdentifier("D1Database"),
          undefined
        ),
      ]),
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("url"),
                  undefined,
                  undefined,
                  factory.createTemplateExpression(
                    factory.createTemplateHead(
                      "https://api.cloudflare.com/client/v4/accounts/"
                    ),
                    [
                      factory.createTemplateSpan(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("client"),
                          factory.createIdentifier("accountId")
                        ),
                        factory.createTemplateMiddle("/d1/database/")
                      ),
                      factory.createTemplateSpan(
                        factory.createIdentifier("databaseId"),
                        factory.createTemplateTail("")
                      ),
                    ]
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("fetchFn"),
                  undefined,
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("client"),
                      factory.createIdentifier("fetch")
                    ),
                    factory.createToken(SyntaxKind.BarBarToken),
                    factory.createIdentifier("fetch")
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("response"),
                  undefined,
                  undefined,
                  factory.createAwaitExpression(
                    factory.createCallExpression(
                      factory.createIdentifier("fetchFn"),
                      undefined,
                      [
                        factory.createIdentifier("url"),
                        factory.createObjectLiteralExpression(
                          [
                            factory.createPropertyAssignment(
                              factory.createIdentifier("method"),
                              factory.createStringLiteral("PATCH")
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("headers"),
                              factory.createObjectLiteralExpression(
                                [
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Authorization"),
                                    factory.createTemplateExpression(
                                      factory.createTemplateHead("Bearer "),
                                      [
                                        factory.createTemplateSpan(
                                          factory.createPropertyAccessExpression(
                                            factory.createIdentifier("client"),
                                            factory.createIdentifier("apiToken")
                                          ),
                                          factory.createTemplateTail("")
                                        ),
                                      ]
                                    )
                                  ),
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Content-Type"),
                                    factory.createStringLiteral("application/json")
                                  ),
                                ],
                                true
                              )
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("body"),
                              factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                  factory.createIdentifier("JSON"),
                                  factory.createIdentifier("stringify")
                                ),
                                undefined,
                                [factory.createIdentifier("request")]
                              )
                            ),
                          ],
                          true
                        ),
                      ]
                    )
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("data"),
                  undefined,
                  undefined,
                  factory.createAsExpression(
                    factory.createAwaitExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("response"),
                          factory.createIdentifier("json")
                        ),
                        undefined,
                        undefined
                      )
                    ),
                    factory.createKeywordTypeNode(SyntaxKind.AnyKeyword)
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createReturnStatement(
            factory.createAsExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier("data"),
                factory.createIdentifier("result")
              ),
              factory.createTypeReferenceNode(
                factory.createIdentifier("D1Database"),
                undefined
              )
            )
          ),
        ],
        true
      )
    )
  );

  // listDatabases function
  nodes.push(
    factory.createFunctionDeclaration(
      [
        factory.createToken(SyntaxKind.ExportKeyword),
        factory.createToken(SyntaxKind.AsyncKeyword),
      ],
      undefined,
      factory.createIdentifier("listDatabases"),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("client"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1HttpClient"),
            undefined
          ),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("options"),
          factory.createToken(SyntaxKind.QuestionToken),
          factory.createTypeReferenceNode(
            factory.createIdentifier("ListDatabasesOptions"),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(factory.createIdentifier("Promise"), [
        factory.createArrayTypeNode(
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1Database"),
            undefined
          )
        ),
      ]),
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("params"),
                  undefined,
                  undefined,
                  factory.createNewExpression(
                    factory.createIdentifier("URLSearchParams"),
                    undefined,
                    []
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createIfStatement(
            factory.createBinaryExpression(
              factory.createIdentifier("options"),
              factory.createToken(SyntaxKind.AmpersandAmpersandToken),
              factory.createPropertyAccessExpression(
                factory.createIdentifier("options"),
                factory.createIdentifier("page")
              )
            ),
            factory.createBlock(
              [
                factory.createExpressionStatement(
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("params"),
                      factory.createIdentifier("append")
                    ),
                    undefined,
                    [
                      factory.createStringLiteral("page"),
                      factory.createCallExpression(
                        factory.createIdentifier("String"),
                        undefined,
                        [
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier("options"),
                            factory.createIdentifier("page")
                          ),
                        ]
                      ),
                    ]
                  )
                ),
              ],
              true
            ),
            undefined
          ),
          factory.createIfStatement(
            factory.createBinaryExpression(
              factory.createIdentifier("options"),
              factory.createToken(SyntaxKind.AmpersandAmpersandToken),
              factory.createPropertyAccessExpression(
                factory.createIdentifier("options"),
                factory.createIdentifier("per_page")
              )
            ),
            factory.createBlock(
              [
                factory.createExpressionStatement(
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("params"),
                      factory.createIdentifier("append")
                    ),
                    undefined,
                    [
                      factory.createStringLiteral("per_page"),
                      factory.createCallExpression(
                        factory.createIdentifier("String"),
                        undefined,
                        [
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier("options"),
                            factory.createIdentifier("per_page")
                          ),
                        ]
                      ),
                    ]
                  )
                ),
              ],
              true
            ),
            undefined
          ),
          factory.createIfStatement(
            factory.createBinaryExpression(
              factory.createIdentifier("options"),
              factory.createToken(SyntaxKind.AmpersandAmpersandToken),
              factory.createPropertyAccessExpression(
                factory.createIdentifier("options"),
                factory.createIdentifier("name")
              )
            ),
            factory.createBlock(
              [
                factory.createExpressionStatement(
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("params"),
                      factory.createIdentifier("append")
                    ),
                    undefined,
                    [
                      factory.createStringLiteral("name"),
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier("options"),
                        factory.createIdentifier("name")
                      ),
                    ]
                  )
                ),
              ],
              true
            ),
            undefined
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("queryString"),
                  undefined,
                  undefined,
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("params"),
                      factory.createIdentifier("toString")
                    ),
                    undefined,
                    []
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("url"),
                  undefined,
                  undefined,
                  factory.createTemplateExpression(
                    factory.createTemplateHead(
                      "https://api.cloudflare.com/client/v4/accounts/"
                    ),
                    [
                      factory.createTemplateSpan(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("client"),
                          factory.createIdentifier("accountId")
                        ),
                        factory.createTemplateMiddle("/d1/database")
                      ),
                      factory.createTemplateSpan(
                        factory.createConditionalExpression(
                          factory.createIdentifier("queryString"),
                          factory.createToken(SyntaxKind.QuestionToken),
                          factory.createTemplateExpression(
                            factory.createTemplateHead("?"),
                            [
                              factory.createTemplateSpan(
                                factory.createIdentifier("queryString"),
                                factory.createTemplateTail("")
                              ),
                            ]
                          ),
                          factory.createToken(SyntaxKind.ColonToken),
                          factory.createStringLiteral("")
                        ),
                        factory.createTemplateTail("")
                      ),
                    ]
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("fetchFn"),
                  undefined,
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("client"),
                      factory.createIdentifier("fetch")
                    ),
                    factory.createToken(SyntaxKind.BarBarToken),
                    factory.createIdentifier("fetch")
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("response"),
                  undefined,
                  undefined,
                  factory.createAwaitExpression(
                    factory.createCallExpression(
                      factory.createIdentifier("fetchFn"),
                      undefined,
                      [
                        factory.createIdentifier("url"),
                        factory.createObjectLiteralExpression(
                          [
                            factory.createPropertyAssignment(
                              factory.createIdentifier("method"),
                              factory.createStringLiteral("GET")
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("headers"),
                              factory.createObjectLiteralExpression(
                                [
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Authorization"),
                                    factory.createTemplateExpression(
                                      factory.createTemplateHead("Bearer "),
                                      [
                                        factory.createTemplateSpan(
                                          factory.createPropertyAccessExpression(
                                            factory.createIdentifier("client"),
                                            factory.createIdentifier("apiToken")
                                          ),
                                          factory.createTemplateTail("")
                                        ),
                                      ]
                                    )
                                  ),
                                ],
                                true
                              )
                            ),
                          ],
                          true
                        ),
                      ]
                    )
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("data"),
                  undefined,
                  undefined,
                  factory.createAsExpression(
                    factory.createAwaitExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("response"),
                          factory.createIdentifier("json")
                        ),
                        undefined,
                        undefined
                      )
                    ),
                    factory.createKeywordTypeNode(SyntaxKind.AnyKeyword)
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createReturnStatement(
            factory.createAsExpression(
              factory.createBinaryExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier("data"),
                  factory.createIdentifier("result")
                ),
                factory.createToken(SyntaxKind.BarBarToken),
                factory.createArrayLiteralExpression([], false)
              ),
              factory.createArrayTypeNode(
                factory.createTypeReferenceNode(
                  factory.createIdentifier("D1Database"),
                  undefined
                )
              )
            )
          ),
        ],
        true
      )
    )
  );

  // getDatabase function
  nodes.push(
    factory.createFunctionDeclaration(
      [
        factory.createToken(SyntaxKind.ExportKeyword),
        factory.createToken(SyntaxKind.AsyncKeyword),
      ],
      undefined,
      factory.createIdentifier("getDatabase"),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("client"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier("D1HttpClient"),
            undefined
          ),
          undefined
        ),
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("databaseId"),
          undefined,
          factory.createKeywordTypeNode(SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(factory.createIdentifier("Promise"), [
        factory.createTypeReferenceNode(
          factory.createIdentifier("D1Database"),
          undefined
        ),
      ]),
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("url"),
                  undefined,
                  undefined,
                  factory.createTemplateExpression(
                    factory.createTemplateHead(
                      "https://api.cloudflare.com/client/v4/accounts/"
                    ),
                    [
                      factory.createTemplateSpan(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("client"),
                          factory.createIdentifier("accountId")
                        ),
                        factory.createTemplateMiddle("/d1/database/")
                      ),
                      factory.createTemplateSpan(
                        factory.createIdentifier("databaseId"),
                        factory.createTemplateTail("")
                      ),
                    ]
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("fetchFn"),
                  undefined,
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier("client"),
                      factory.createIdentifier("fetch")
                    ),
                    factory.createToken(SyntaxKind.BarBarToken),
                    factory.createIdentifier("fetch")
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("response"),
                  undefined,
                  undefined,
                  factory.createAwaitExpression(
                    factory.createCallExpression(
                      factory.createIdentifier("fetchFn"),
                      undefined,
                      [
                        factory.createIdentifier("url"),
                        factory.createObjectLiteralExpression(
                          [
                            factory.createPropertyAssignment(
                              factory.createIdentifier("method"),
                              factory.createStringLiteral("GET")
                            ),
                            factory.createPropertyAssignment(
                              factory.createIdentifier("headers"),
                              factory.createObjectLiteralExpression(
                                [
                                  factory.createPropertyAssignment(
                                    factory.createStringLiteral("Authorization"),
                                    factory.createTemplateExpression(
                                      factory.createTemplateHead("Bearer "),
                                      [
                                        factory.createTemplateSpan(
                                          factory.createPropertyAccessExpression(
                                            factory.createIdentifier("client"),
                                            factory.createIdentifier("apiToken")
                                          ),
                                          factory.createTemplateTail("")
                                        ),
                                      ]
                                    )
                                  ),
                                ],
                                true
                              )
                            ),
                          ],
                          true
                        ),
                      ]
                    )
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("data"),
                  undefined,
                  undefined,
                  factory.createAsExpression(
                    factory.createAwaitExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("response"),
                          factory.createIdentifier("json")
                        ),
                        undefined,
                        undefined
                      )
                    ),
                    factory.createKeywordTypeNode(SyntaxKind.AnyKeyword)
                  )
                ),
              ],
              NodeFlags.Const
            )
          ),
          factory.createReturnStatement(
            factory.createAsExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier("data"),
                factory.createIdentifier("result")
              ),
              factory.createTypeReferenceNode(
                factory.createIdentifier("D1Database"),
                undefined
              )
            )
          ),
        ],
        true
      )
    )
  );

  return nodes;
}
